### ISSUE TITLE
System.IO.DirectoryNotFoundException: 'C:\root\.nuget\packages\microsoft.aspnetcore.identity.ui\5.0.1\staticwebassets\V4\'

### ISSUE THREAD

**Issue by elgunatahan** [dahlsailrunner/docker-fundamentals#4]
Hi,

I am newest with docker. I get an eror on running solution. I attach exception below. Need your help :)
![Globomantics](https://user-images.githubusercontent.com/27769056/118340071-59341380-b523-11eb-9577-b38d43408ffb.png)

**Comment by elgunatahan** [comment]
smtp4dev images in use and container is in running state. Also i change SmtpPort in appsettings. 
I choose as startup project these belows ones. 
![Globomantics-set-startup](https://user-images.githubusercontent.com/27769056/118343067-60611e80-b52f-11eb-8af4-950e04d8af72.png)

**Comment by dahlsailrunner** [comment]
The single startup project you want is `docker-compose`.  Have you restored all of the NuGet packages for the project?

**Comment by elgunatahan** [comment]
Thank you so much. I resolve by the running only docker-compose.
I'm confused a little bit. I didn't get that you published  the final version of the solution for helping as. So i tried to make same things by video. Now i understand all :).

**Comment by elgunatahan** [comment]
Maybe it can be great if you can share the initial state of the solution in your repo also in branch. By this way we can try to do same things by the video. Thank you so much about couse, it is greatful :)
