### ISSUE TITLE
Separate branch for pre docker implemetation

### ISSUE THREAD

**Issue by amitlatthe** [dahlsailrunner/docker-fundamentals#6]
Hi,

I am referring pluralsight course. After cloning main branch, getting errors because this is final version of code with docker implementation.
Would be helpful if you could provide section-wise branch. I am referring section 2 and not able to fix issues.

Thanks in advance

**Comment by dahlsailrunner** [comment]
Try downloading the "exercise files" from the Pluralsight course itself.  That has a `begin` and `end` folder for each module and should have what you are looking for.

**Comment by amitlatthe** [comment]
Thank You!
